-- MySQL Script generated by MySQL Workbench
-- Fri Aug 26 16:28:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_autonominas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_autonominas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_autonominas` DEFAULT CHARACTER SET utf8 ;
USE `db_autonominas` ;

-- -----------------------------------------------------
-- Table `db_autonominas`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autonominas`.`tb_categorias` (
  `id_categorias` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_autonominas`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autonominas`.`tb_usuarios` (
  `id_usuarios` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_autonominas`.`tb_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autonominas`.`tb_post` (
  `id_post` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `conteudo` VARCHAR(255) NOT NULL,
  `date_post` DATETIME NOT NULL,
  `id_categoria_fk` BIGINT NOT NULL,
  `id_usuario_fk` BIGINT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_tb_post_tb_categorias_idx` (`id_categoria_fk` ASC) VISIBLE,
  INDEX `fk_tb_post_tb_usuarios1_idx` (`id_usuario_fk` ASC) VISIBLE,
  CONSTRAINT `fk_tb_post_tb_categorias`
    FOREIGN KEY (`id_categoria_fk`)
    REFERENCES `db_autonominas`.`tb_categorias` (`id_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_post_tb_usuarios1`
    FOREIGN KEY (`id_usuario_fk`)
    REFERENCES `db_autonominas`.`tb_usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
